include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    inference_failure_on_untyped_parameter: ignore
    public_member_api_docs: ignore
    argument_type_not_assignable: ignore
    map_value_type_not_assignable: ignore
    invalid_assignment: ignore
    avoid_dynamic_calls: ignore
    one_member_abstracts: ignore
    avoid_positional_boolean_parameters: ignore
    prefer_asserts_with_message: ignore
    sort_pub_dependencies: false
