//==============================================================================
// Generated Date: 2024-10-13T23:28:13.387146
//
// Generated By language_helper - Do Not Modify By Hand
//==============================================================================

// ignore_for_file: prefer_single_quotes

part of '../language_data.dart';

const analysisLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: ./lib/core/utils/price_utils.dart
  ///===========================================================================
  "@path_./lib/core/utils/price_utils.dart": '',
  'Tối đa': 'Tối đa',

  ///===========================================================================
  /// Path: ./lib/infrastructure/respositories/local_auth_repository_impl.dart
  ///===========================================================================
  "@path_./lib/infrastructure/respositories/local_auth_repository_impl.dart":
      '',
  'Sai tên đăng nhập hoặc mật khẩu': 'Sai tên đăng nhập hoặc mật khẩu',
  'Không có thông tin đăng nhập được lưu':
      'Không có thông tin đăng nhập được lưu',

  ///===========================================================================
  /// Path: ./lib/infrastructure/respositories/backup_restore_repository_impl.dart
  ///===========================================================================
  "@path_./lib/infrastructure/respositories/backup_restore_repository_impl.dart":
      '',
  'Lưu Bản Sao Lưu': 'Lưu Bản Sao Lưu',
  'Chọn Bản Sao Lưu': 'Chọn Bản Sao Lưu',

  ///===========================================================================
  /// Path: ./lib/infrastructure/services/database_service_impl.dart
  ///===========================================================================
  "@path_./lib/infrastructure/services/database_service_impl.dart": '',
  'Không thể kết nối được với máy chủ': 'Không thể kết nối được với máy chủ',

  ///===========================================================================
  /// Path: ./lib/domain/usecases/data_services/import_data_usecase.dart
  ///===========================================================================
  "@path_./lib/domain/usecases/data_services/import_data_usecase.dart": '',
  'Đã có lỗi xảy ra khi nhập dữ liệu, vui lòng kiểm tra lại dữ liệu mẫu':
      'Đã có lỗi xảy ra khi nhập dữ liệu, vui lòng kiểm tra lại dữ liệu mẫu',

  ///===========================================================================
  /// Path: ./lib/domain/entities/order_status.dart
  ///===========================================================================
  "@path_./lib/domain/entities/order_status.dart": '',
  'Đã tạo': 'Đã tạo',
  'Đã thanh toán': 'Đã thanh toán',
  'Đã huỷ': 'Đã huỷ',

  ///===========================================================================
  /// Path: ./lib/presentation/riverpod/notifiers/login_provider.dart
  ///===========================================================================
  "@path_./lib/presentation/riverpod/notifiers/login_provider.dart": '',
  'Đã có lỗi không xác định!': 'Đã có lỗi không xác định!',
  // 'Đã có lỗi không xác định!': 'Đã có lỗi không xác định!',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/views/home_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/home_view.dart": '',
  'Tổng Quan': 'Tổng Quan',
  'Đơn Hàng': 'Đơn Hàng',
  'Sản Phẩm': 'Sản Phẩm',
  'Báo Cáo': 'Báo Cáo',
  'Cài Đặt': 'Cài Đặt',
  'Đăng Xuất': 'Đăng Xuất',

  ///===========================================================================
  /// Path: ./lib/presentation/views/products_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/products_view.dart": '',
  'Tìm Kiếm': 'Tìm Kiếm',
  'STT': 'STT',
  'ID': 'ID',
  'Tên': 'Tên',
  'Giá nhập': 'Giá nhập',
  'Giá bán': 'Giá bán',
  'Loại hàng': 'Loại hàng',
  'Số lượng': 'Số lượng',
  'Hành động': 'Hành động',
  'Thông báo': 'Thông báo',
  'Bạn cần có it nhất một loại hàng để có thể thêm sản phẩm.\n\n'
          'Bạn có muốn thêm loại hàng không?':
      'Bạn cần có it nhất một loại hàng để có thể thêm sản phẩm.\n\n'
          'Bạn có muốn thêm loại hàng không?',
  'Đồng ý': 'Đồng ý',
  'Huỷ': 'Huỷ',
  'Xác nhận': 'Xác nhận',
  'Bạn có chắc muốn xoá sản phẩm @{name} không?':
      'Bạn có chắc muốn xoá sản phẩm @{name} không?',
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Bộ lọc': 'Bộ lọc',
  'OK': 'OK',
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Sắp xếp': 'Sắp xếp',
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Nhập Excel': 'Nhập Excel',
  // 'Nhập Excel': 'Nhập Excel',  // Duplicated
  'Bạn chưa chọn tệp hoặc tệp chưa được hỗ trợ':
      'Bạn chưa chọn tệp hoặc tệp chưa được hỗ trợ',
  // 'Nhập Excel': 'Nhập Excel',  // Duplicated
  'Dữ liệu bạn đang chọn trống!': 'Dữ liệu bạn đang chọn trống!',
  'Ok': 'Ok',
  // 'Nhập Excel': 'Nhập Excel',  // Duplicated
  'Có @{count} sản phẩm trong dữ liệu cần nhập. '
          'Dữ liệu mới sẽ thay thế dữ liệu cũ và không thể hoàn tác.\n\n'
          'Bạn có muốn tiếp tục không?':
      'Có @{count} sản phẩm trong dữ liệu cần nhập. '
          'Dữ liệu mới sẽ thay thế dữ liệu cũ và không thể hoàn tác.\n\n'
          'Bạn có muốn tiếp tục không?',
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  // 'Thông báo': 'Thông báo',  // Duplicated
  // 'Bạn cần có it nhất một loại hàng để có thể thêm sản phẩm.\n\n' 'Bạn có muốn thêm loại hàng không?': 'Bạn cần có it nhất một loại hàng để có thể thêm sản phẩm.\n\n' 'Bạn có muốn thêm loại hàng không?',  // Duplicated
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Không': 'Không',
  'Tên tăng dần': 'Tên tăng dần',
  'Tên giảm dần': 'Tên giảm dần',
  'Giá tăng dần': 'Giá tăng dần',
  'Giá giảm dần': 'Giá giảm dần',
  'Số lượng tăng đần': 'Số lượng tăng đần',
  'Số lượng giảm đần': 'Số lượng giảm đần',
  'Trở về': 'Trở về',

  ///===========================================================================
  /// Path: ./lib/presentation/views/login_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/login_view.dart": '',
  'Chào mừng bạn trở lại!': 'Chào mừng bạn trở lại!',
  'Đăng nhập': 'Đăng nhập',
  'Chào mừng bạn đã trở lại! Vui lòng đăng nhập để tiếp tục':
      'Chào mừng bạn đã trở lại! Vui lòng đăng nhập để tiếp tục',
  'Tên tài khoản': 'Tên tài khoản',
  'Mật khẩu': 'Mật khẩu',
  'Nhớ thông tin của tôi': 'Nhớ thông tin của tôi',
  'Đăng Nhập': 'Đăng Nhập',
  'Cấu hình máy chủ': 'Cấu hình máy chủ',
  'Cấu Hình Máy Chủ': 'Cấu Hình Máy Chủ',
  'Lưu': 'Lưu',
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Đang tự động đăng nhập...': 'Đang tự động đăng nhập...',
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/views/settings_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/settings_view.dart": '',
  'Ngôn Ngữ': 'Ngôn Ngữ',
  'Chế Độ Tối': 'Chế Độ Tối',
  'Số dòng mỗi trang khi phân trang': 'Số dòng mỗi trang khi phân trang',
  'Sao Lưu và Khôi Phục': 'Sao Lưu và Khôi Phục',
  'Sao Lưu': 'Sao Lưu',
  'Khôi Phục': 'Khôi Phục',

  ///===========================================================================
  /// Path: ./lib/presentation/views/dashboard_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/dashboard_view.dart": '',
  'Biểu đồ doanh thu theo ngày trong tháng @{month}':
      'Biểu đồ doanh thu theo ngày trong tháng @{month}',
  'Chi tiết 3 đơn hàng gần nhất': 'Chi tiết 3 đơn hàng gần nhất',
  'Top 5 sản phẩm bán chạy': 'Top 5 sản phẩm bán chạy',
  'Top 5 sản phẩm sắp hết hàng (số lượng < 5)':
      'Top 5 sản phẩm sắp hết hàng (số lượng < 5)',
  'Tổng doanh thu trong ngày': 'Tổng doanh thu trong ngày',
  '@{dailyRevenue} đồng': '@{dailyRevenue} đồng',
  'Tổng số đơn hàng trong ngày': 'Tổng số đơn hàng trong ngày',
  '@{count} đơn': '@{count} đơn',
  'Tổng số sản phẩm': 'Tổng số sản phẩm',
  '@{count} sản phẩm': '@{count} sản phẩm',

  ///===========================================================================
  /// Path: ./lib/presentation/views/orders_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/orders_view.dart": '',
  // 'STT': 'STT',  // Duplicated
  'Ngày Giờ': 'Ngày Giờ',
  'Trạng Thái': 'Trạng Thái',
  // 'Hành động': 'Hành động',  // Duplicated
  // 'Xác nhận': 'Xác nhận',  // Duplicated
  'Bạn có chắc muốn xoá đơn này không?': 'Bạn có chắc muốn xoá đơn này không?',
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  // 'Bộ lọc': 'Bộ lọc',  // Duplicated
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/views/report_view.dart
  ///===========================================================================
  "@path_./lib/presentation/views/report_view.dart": '',
  'Sản phẩm và số lượng bán tương ứng:': 'Sản phẩm và số lượng bán tương ứng:',
  'Doanh thu và lợi nhuận:': 'Doanh thu và lợi nhuận:',
  // 'Bộ lọc': 'Bộ lọc',  // Duplicated
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/image_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/image_dialog.dart": '',
  'Thêm Ảnh': 'Thêm Ảnh',
  'Thêm': 'Thêm',
  // 'Huỷ': 'Huỷ',  // Duplicated
  'Xoá Ảnh': 'Xoá Ảnh',
  'Bạn có chắc muốn xoá ảnh này không?': 'Bạn có chắc muốn xoá ảnh này không?',
  'Có': 'Có',
  // 'Không': 'Không',  // Duplicated
  'Vui lòng chọn ảnh từ đường dẫn\ntừ máy hoặc internet':
      'Vui lòng chọn ảnh từ đường dẫn\ntừ máy hoặc internet',
  'Đường dẫn': 'Đường dẫn',
  'Chọn ảnh từ máy': 'Chọn ảnh từ máy',

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/category_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/category_dialog.dart": '',
  'Chi Tiết Loại Hàng': 'Chi Tiết Loại Hàng',
  'Thêm Loại Hàng': 'Thêm Loại Hàng',
  'Sửa Loại Hàng': 'Sửa Loại Hàng',
  // 'Xác nhận': 'Xác nhận',  // Duplicated
  'Bạn có chắc muốn xoá loại hàng @{name} không?':
      'Bạn có chắc muốn xoá loại hàng @{name} không?',
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  // 'Tên': 'Tên',  // Duplicated
  'Mô tả': 'Mô tả',
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/order_filter_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/order_filter_dialog.dart": '',
  'Lọc theo khoảng thời gian': 'Lọc theo khoảng thời gian',
  'Từ': 'Từ',
  'Đến': 'Đến',

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/order_form_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/order_form_dialog.dart": '',
  'Chọn Sản Phẩm': 'Chọn Sản Phẩm',
  'Có sản phẩm không đủ số lượng trong kho nên không thể Sao chép.\n'
          'Vui lòng cập nhật thêm sản phẩm để tiếp tục!':
      'Có sản phẩm không đủ số lượng trong kho nên không thể Sao chép.\n'
          'Vui lòng cập nhật thêm sản phẩm để tiếp tục!',
  // 'Ngày Giờ': 'Ngày Giờ',  // Duplicated
  'Trạng thái': 'Trạng thái',
  // 'Trạng thái': 'Trạng thái',  // Duplicated
  // 'STT': 'STT',  // Duplicated
  'Tên Sản Phẩm': 'Tên Sản Phẩm',
  'Số Lượng': 'Số Lượng',
  'Đơn Giá': 'Đơn Giá',
  'Thành Tiền': 'Thành Tiền',
  'Hành Động': 'Hành Động',

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/product_form_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/product_form_dialog.dart": '',
  'Mã sản phẩm': 'Mã sản phẩm',
  'Tên sản phẩm': 'Tên sản phẩm',
  // 'Giá nhập': 'Giá nhập',  // Duplicated
  'Vui lòng chỉ nhập số': 'Vui lòng chỉ nhập số',
  // 'Giá bán': 'Giá bán',  // Duplicated
  // 'Vui lòng chỉ nhập số': 'Vui lòng chỉ nhập số',  // Duplicated
  // 'Số lượng': 'Số lượng',  // Duplicated
  // 'Vui lòng chỉ nhập số': 'Vui lòng chỉ nhập số',  // Duplicated
  // 'Loại hàng': 'Loại hàng',  // Duplicated
  // 'Loại hàng': 'Loại hàng',  // Duplicated
  'Hình ảnh': 'Hình ảnh',
  'Chưa có hình ảnh': 'Chưa có hình ảnh',
  // 'Mô tả': 'Mô tả',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/order_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/order_dialog.dart": '',
  'Thông Tin Đơn': 'Thông Tin Đơn',
  'Thêm Đơn': 'Thêm Đơn',
  'Sửa Đơn': 'Sửa Đơn',
  'Chép Đơn': 'Chép Đơn',
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/page_chooser_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/page_chooser_dialog.dart": '',
  'Bạn cần nhập số trang': 'Bạn cần nhập số trang',
  'Số trang phải là số nguyên': 'Số trang phải là số nguyên',
  'Số trang phải >= 1': 'Số trang phải >= 1',
  'Số trang phải <= @{totalPage}': 'Số trang phải <= @{totalPage}',
  'Chọn trang': 'Chọn trang',
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/product_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/product_dialog.dart": '',
  'Thông Tin Sản Phẩm': 'Thông Tin Sản Phẩm',
  'Thêm Sản Phẩm': 'Thêm Sản Phẩm',
  'Sửa Sản Phẩm': 'Sửa Sản Phẩm',
  'Chép Sản Phẩm': 'Chép Sản Phẩm',
  // 'Xác nhận': 'Xác nhận',  // Duplicated
  // 'Bạn có chắc muốn xoá sản phẩm @{name} không?': 'Bạn có chắc muốn xoá sản phẩm @{name} không?',  // Duplicated
  // 'Đồng ý': 'Đồng ý',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated
  // 'OK': 'OK',  // Duplicated
  // 'Huỷ': 'Huỷ',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/report_filter_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/report_filter_dialog.dart": '',
  // 'Lọc theo khoảng thời gian': 'Lọc theo khoảng thời gian',  // Duplicated
  // 'Từ': 'Từ',  // Duplicated
  // 'Đến': 'Đến',  // Duplicated

  ///===========================================================================
  /// Path: ./lib/presentation/widgets/product_filter_dialog.dart
  ///===========================================================================
  "@path_./lib/presentation/widgets/product_filter_dialog.dart": '',
  'Lọc theo mức giá': 'Lọc theo mức giá',
  // 'Từ': 'Từ',  // Duplicated
  'Không được bỏ trống': 'Không được bỏ trống',
  'Phải là số nguyên': 'Phải là số nguyên',
  // 'Đến': 'Đến',  // Duplicated
  // 'Tối đa': 'Tối đa',  // Duplicated
  // 'Không được bỏ trống': 'Không được bỏ trống',  // Duplicated
  // 'Phải là số nguyên': 'Phải là số nguyên',  // Duplicated
  'Lọc theo loại hàng': 'Lọc theo loại hàng',
  // 'Loại hàng': 'Loại hàng',  // Duplicated
  'Tất cả': 'Tất cả',
};
